name: GoCD
markdown: redcarpet
  extensions: ["tables"]
highlighter: null
future: false
navigation:
- root: Blog
  url: /blog.html
  icon: icon-comment
- root: Learn more
  url: #
  icon: icon-help-circled-1 
  first-level:
    - text: Why Go?
      url: /learn-more/why-go.html
    - text: Help Doc
      url: http://www.thoughtworks.com/products/docs/go/14.1/help/
      target: blank
- root: Contribute
  url: #
  icon: icon-star-5
  first-level:
    - text: Get started
      url: /contribute/
    - text: Contribution Guide
      url: /contribute/contribution-guide.html
    - text: Roadmap
      url: /contribute/roadmap.html
    - text: CLA
      url: /contribute/cla.html
    - text: Contributors
      url: /contribute/contributors.html
    - text: Open Issues
      url: https://github.com/gocd/gocd/issues?page=1&state=open
      target: blank

- root: Community
  url: #
  icon: icon-group
  first-level:
    - text: Events
      url: /community/events.html
    - text: Resources
      url: /community/resources.html
    - text: Plugins
      url: /community/plugins.html
- root: Download
  url: /download/
  icon: icon-download
